version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: sqlite
    ports:
      - '1337:1337'
    volumes:
      - ./strapi:/srv/app
